export const movies =  [
    
    {
title:"Travel",
plot:"Supernatural Powers shown in the movie",
price:"199",
rating:"8.9",
image:"/travel.png",
stars:0,
fav: false,
cart: false,
    },
    {
        title:"Assassin ",
        plot:"Supernatural Powers shown in the movie",
        price:"189",
        rating:"8.7",
        image:"/assassin.png",
        stars:0,
        fav: false,
        cart: false,
            },
            {
                title:"Avengers",
                plot:"Supernatural Powers shown in the movie",
                price:"299",
                rating:"7.9",
                image:"/avengers.png",
                        stars:0,
                        fav: false,
                        cart: false,
                            },
                            {
                                title:"Beacn bum",
                                plot:"Supernatural Powers shown in the movie",
                                price:"199",
                                rating:"8.9",
                                image:"/beacn bum.png",
                                stars:0,
                                fav: false,
                                cart: false,
                                    },
                                    {
                                        title:"Beauty and Beast",
                                        plot:"Supernatural Powers shown in the movie",
                                        price:"299",
                                        rating:"9.9",
                                        image:"/beauty and beast.png",
                                        stars:0,
                                        fav: false,
                                        cart: false,
                                            },
                                            {
                                                title:"Black Widow",
                                                plot:"Supernatural Powers shown in the movie",
                                                price:"199",
                                                rating:"8.0",
                                                image:"/black widow.png",
                                                stars:0,
                                                fav: false,
                                                cart: false,
                                                    },
                                                    {
                                                        title:"Brahmastra",
                                                        plot:"Supernatural Powers shown in the movie",
                                                        price:"199",
                                                        rating:"8.9",
                                                        image:"/brahmastra.png",
                                                        stars:0,
                                                        fav: false,
                                                        cart: false,
                                                            },
                                                            {
                                                                title:"Dark",
                                                                plot:"Supernatural Powers shown in the movie",
                                                                price:"299",
                                                                rating:"9.9",
                                                                image:"/dark.png",
                                                                stars:0,
                                                                fav: false,
                                                                cart: false,
                                                                    },
                                                                    {
                                                                        title:"Dora",
                                                                        plot:"Supernatural Powers shown in the movie",
                                                                        price:"299",
                                                                        rating:"9.9",
                                                                        image:"/dora.png",
                                                                        stars:0,
                                                                        fav: false,
                                                                        cart: false,
                                                                            },
                                                                            {
                                                                                title:"Guardians",
                                                                                plot:"Supernatural Powers shown in the movie",
                                                                                price:"299",
                                                                                rating:"9.9",
                                                                                image:"/guardians.png",
                                                                                stars:0,
                                                                                fav: false,
                                                                                cart: false,
                                                                                    },
                                                                                    {
                                                                                        title:"Harry Potter",
                                                                                        plot:"Supernatural Powers shown in the movie",
                                                                                        price:"299",
                                                                                        rating:"9.9",
                                                                                        image:"/harrypotter.png",
                                                                                        stars:0,
                                                                                        fav: false,
                                                                                        cart: false,
                                                                                            },
                                                                                            {
                                                                                                title:"Matrix",
                                                                                                plot:"Supernatural Powers shown in the movie",
                                                                                                price:"299",
                                                                                                rating:"9.9",
                                                                                                image:"/matix.png",
                                                                                                stars:0,
                                                                                                fav: false,
                                                                                                cart: false,
                                                                                                    },
                                                                                                    {
                                                                                                        title:"Oppenheimer",
                                                                                                        plot:"Supernatural Powers shown in the movie",
                                                                                                        price:"299",
                                                                                                        rating:"9.9",
                                                                                                        image:"/oppenheimer.png",
                                                                                                        stars:0,
                                                                                                        fav: false,
                                                                                                        cart: false,
                                                                                                            },
                                                                                                            {
                                                                                                                title:"Saint",
                                                                                                                plot:"Supernatural Powers shown in the movie",
                                                                                                                price:"299",
                                                                                                                rating:"9.9",
                                                                                                                image:"/saint.png",
                                                                                                                stars:0,
                                                                                                                fav: false,
                                                                                                                cart: false,
                                                                                                                    },
                                                                                                                    {
                                                                                                                        title:"The Thing",
                                                                                                                        plot:"Supernatural Powers shown in the movie",
                                                                                                                        price:"299",
                                                                                                                        rating:"9.9",
                                                                                                                        image:"/the thing.png",
                                                                                                                        stars:0,
                                                                                                                        fav: false,
                                                                                                                        cart: false,
                                                                                                                            },
                                                                                                                            {
                                                                                                                                title:"Thor",
                                                                                                                                plot:"Supernatural Powers shown in the movie",
                                                                                                                                price:"299",
                                                                                                                                rating:"9.9",
                                                                                                                                image:"/thor.png",
                                                                                                                                stars:0,
                                                                                                                                fav: false,
                                                                                                                                cart: false,
                                                                                                                                    },
                                                                                                                                    

]                                                                                                                       